# 5.20 NumPy Array Indexing (Pierian Data)

Indexing and Selection

In [2]:
import numpy as np

Setting up NumPy array to use in the example

In [5]:
arr = np.arange(0,11)

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Getting element at index

In [7]:
arr[8]

8

# Slice notation (for vecter)

In [8]:
arr[1:5]

array([1, 2, 3, 4])

In [10]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [11]:
arr[:5]

array([0, 1, 2, 3, 4])

# Broadcasting     
  Setting the slice part to one number    

In [12]:
arr[:5] = 100

In [13]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

##  If you copy an array is the old array effected when change the new array? Yes
In Broadcasting if copy value into another array and broadcasting on the new array the old array is also changed.

In [14]:
old_arr = np.arange(0,10)

In [15]:
old_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
new_arr = old_arr[:5]

In [17]:
new_arr

array([0, 1, 2, 3, 4])

The slice notation of new_arr[:] uses the whole array

In [18]:
new_arr[:] = 100

In [19]:
new_arr

array([100, 100, 100, 100, 100])

See the old array is also changed

In [20]:
old_arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

### conclusion: The old array is changed

## How to make changes to new array not effect the old array when using the slice method ?   

## Use to copy method

In [23]:
old_array = np.arange(0,10)

In [24]:
old_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
new_array = old_array.copy()

In [26]:
new_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
new_new_array = new_array[:5]

In [28]:
new_new_array

array([0, 1, 2, 3, 4])

In [29]:
new_new_array[:] = 100

In [30]:
new_array

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [31]:
old_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### conclusion : The old array is NOT effected because we copy it. 

# Indexing Matrix

Setting up sample matrix

In [3]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [4]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

### Double Bracket Notation

In [5]:
arr_2d[1][1]

25

### Single Comma Notation

In [7]:
arr_2d[1,1]

25

### Getting whole row of a matrix

In [8]:
arr_2d[1]

array([20, 25, 30])

### Slice Notation for Matrics 

In [11]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [13]:
arr_2d[:,1:]

array([[10, 15],
       [25, 30],
       [40, 45]])

In [9]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

### Condition Selection

Setting up Sample Data

In [17]:
arr_sample = np.arange(1,11)

In [18]:
arr_sample 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
arr_condition = arr_sample > 5

In [20]:
arr_condition

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [21]:
arr_sample[arr_condition]

array([ 6,  7,  8,  9, 10])

In [22]:
arr_sample[arr_sample > 5]

array([ 6,  7,  8,  9, 10])