# 5.18 Numpy Arrays (Pierian Data)

In [2]:
import numpy as np

# Creating NumPy Arrays

In [3]:
grades = np.array([95,88,79,73,97,82])

In [44]:
grades

array([95, 88, 79, 73, 97, 82])

In [45]:
student = np.array(['Tom','Ann','Bill','Joe','Betty','Tim'])

In [46]:
student

array(['Tom', 'Ann', 'Bill', 'Joe', 'Betty', 'Tim'], dtype='<U5')

In [47]:
city_list = ['minneapolis','cleveland','alexandria']
city = np.array( city_list )

In [48]:
city

array(['minneapolis', 'cleveland', 'alexandria'], dtype='<U11')

### Creating NumPy Arrays with three lists

In [49]:
count_list = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]

In [50]:
count_list

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [51]:
count  = np.array(count_list)

This is TWO dimensional Matrix x and y 

In [52]:
count

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Getting element in the Matrix

In [53]:
count[2,3]

12

The shape of this Matrix "count" is the number rows (3) and number of columns (4).   
In Matrix rows then columns is read so this "3 by 4 Matrix"
So there are TWO dimensions.       

In [54]:
count.shape

(3, 4)

Setting our dimensions of the NumPy Array.  

ndmin : int, optional    
Specifies the minimum number of dimensions that the resulting array should have.        
Ones will be pre-pended to the shape as needed to meet this requirement.      

In [55]:
small_count = np.array([1, 2, 3], ndmin=2)

In [56]:
small_count

array([[1, 2, 3]])

In [57]:
small_count.shape

(1, 3)

## Fast ways to generate NumPy arrays

Starting at 0, to 10 with step 2

In [59]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [61]:
np.zeros(3)

array([0., 0., 0.])

Passing Tuple as part of the parameter list

In [63]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [64]:
np.ones((4))

array([1., 1., 1., 1.])

Passing Tuple as part of the parameter list

In [65]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

numpy.linspace(start, stop, num = 50, endpoint = True, retstep = False, dtype = None)         
    
Returns number spaces evenly w.r.t interval. Similiar to arange but instead of step it uses sample number.   

Parameters:   
-> start  : [optional] start of interval range. By default start = 0    
-> stop   : end of interval range    
-> restep : If True, return (samples, step). By deflut restep = False    
-> num    : [int, optional] No. of samples to generate    
-> dtype  : type of output array     

In [68]:
np.linspace(0,5,2)

array([0., 5.])

Identity Matrix ( In this matrix same number columns and rows)

In [70]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Generating Random NumPy Arrays

In [3]:
np.random.rand(5)

array([0.925372  , 0.03820959, 0.14904609, 0.43588   , 0.77733373])

In [4]:
np.random.rand(5,5)

array([[0.46691617, 0.20705708, 0.79448322, 0.69989884, 0.56451178],
       [0.85329714, 0.56949468, 0.64737182, 0.52195793, 0.15536224],
       [0.37502158, 0.41279051, 0.40215795, 0.099091  , 0.97476438],
       [0.65567093, 0.30160168, 0.36970062, 0.92722259, 0.21897841],
       [0.52669313, 0.07612268, 0.90993112, 0.14264367, 0.29075241]])

In [5]:
np.random.randn(2)

array([-1.53608997,  1.34868988])

In [6]:
np.random.randn(2,1)

array([[-0.51677744],
       [ 0.18754507]])

In [7]:
np.random.randint(1,100)

67

In [8]:
np.random.randint(1,100,10)

array([97, 77, 12, 63, 80, 30, 68, 68, 65,  5])

# Important Methods 

Making matrix to uses as in the examples

In [9]:
arr = np.arange(0,25)

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

Making matrix to uses as in the examples

In [11]:
ranarr = np.random.randint(0,50,10)

In [12]:
ranarr

array([28, 46, 39, 21, 24, 37, 21, 13, 14, 39])

If you want 5 By 5 Matrix so you have NumPy Array equal 25 elements

In [13]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [16]:
ranarr.max()

46

In [17]:
ranarr.min()

13

The index of the maximum value

In [18]:
ranarr.argmax()

1

The index of the minimum value

In [19]:
ranarr.argmin()

7

You see (25, ) means this is one dimensional matrix 

In [20]:
arr.shape

(25,)

In [21]:
arr = arr.reshape(5,5)

In [22]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

This is two dimensional matrix

In [23]:
arr.shape

(5, 5)

See the data type

In [24]:
arr.dtype

dtype('int64')